### ISSUE TITLE
Swift Package Manager Support

### ISSUE THREAD

**Issue by wendellli99** [satoshi-takano/OpenGraph#48]
Can we add support for swift package manager? Currently, Xcode has this warning after adding via SPM: 
<img width="578" alt="Screen Shot 2021-06-14 at 1 09 03 PM" src="https://user-images.githubusercontent.com/34215792/121841832-b7663900-cd11-11eb-8be5-e3109aa92bf3.png">

**Comment by satoshi-takano** [comment]
@wendellli99 
Thanks for your report. I've just fixed the warning. Could you please reinstall OpenGraph via SPM? Thanks.

**Comment by wendellli99** [comment]
@satoshi-takano Thank you for replying. I am still seeing the same warning after removing the package, cleaning derived data, and reinstalling it. Is there a specific way to install it?

**Comment by satoshi-takano** [comment]
@wendellli99 
Thanks for reinstalling the package. Could you please try to "File > Swift Packages > Reset Package Cache" and then try to reinstall the package again?

**Comment by wendellli99** [comment]
OK, I finally fixed the issue. Please see my pull request for details.

**Comment by satoshi-takano** [comment]
@wendellli99 Thanks for your Pull Request! I've merged it and have released as 1.3.2.
